### ISSUE TITLE
superfluous modules

### ISSUE THREAD

**Issue by adriaandegroot** [netrunner-pinebook/netrunner-pinebook-calamares#2]
There's a separate module defined for calamares, called `deferred_removal`. While that's OK, you can (better, IMO) use the dummyprocess module which already exists. Then you just need a config file:

 - add an instance to *settings.conf*:
   ```
instances:
  - id: deferred_remove
    config: deferred_remove.conf
    module: dummyprocess
```
 - rename the existing *deferred_remove.desc* to *deferred_remove.conf* and put it in with the rest of the config files.
